name: S3 Sync Actions

on:
  workflow_dispatch:
        push:
            branches: [ main ]

permissions:
    id-token: write
    contents: read

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name:  Checkout repo
              uses: actions/checkout@v2

            - name:  Connect to AWS
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-session-name: awssyncsession
                role-to-assume: ${{secrets.AWS_IAM_ROLE }}
                aws-region: ${{ secrets.AWS_REGION}}

            - name: sync bucket
              run: aws s3 sync ./files/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete






    